export type ThemeProps = {
  "color-neutral-white": string;
  "color-neutral-grey-10": string;
  "color-neutral-grey-20": string;
  "color-neutral-grey-30": string;
  "color-neutral-grey-40": string;
  "color-neutral-grey-50": string;
  "color-neutral-grey-60": string;
  "color-semantic-informative-blue-10": string;
  "color-semantic-informative-blue-50": string;
  "color-semantic-warning-yellow-10": string;
  "color-semantic-warning-yellow-50": string;
  "color-semantic-danger-red-10": string;
  "color-semantic-danger-red-50": string;
  "color-semantic-success-green-10": string;
  "color-semantic-success-green-50": string;
  "font-size-large": "18px";
  "font-size-regular": "16px";
  "font-size-medium": "14px";
  "font-size-small": string;
  "font-size-mini": string;
  "font-weight-lighter": number;
  "font-weight-light": number;
  "font-weight-regular": number;
  "font-weight-medium": number;
  "font-weight-bold": number;
  "font-weight-bolder": number;
};
