import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/styles/global.scss";
import MyImageComponent from "@/pollen/example-component";
import { createStore } from "../../lib/owner-state";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const testState = createStore<{ value: number }>({
    initialState: {
      value: 0,
    },
  });

  testState.setState({ value: 1 });

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <MyImageComponent
          src="https://avatars.githubusercontent.com/u/82906575?s=200&v=4"
          alt="Descrição da imagem"
          objectFit="cover"
          sizing={{
            width: "w-fx-120",
          }}
        /> */}
        {children}
      </body>
    </html>
  );
}
